name: coffee_shop_app
description: "A premium Flutter coffee ordering application with Supabase backend."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Supabase Backend
  supabase_flutter: ^2.8.4

  # State Management
  get: ^4.7.2

  # Image Caching
  cached_network_image: ^3.4.1

  # Responsive Design
  flutter_screenutil: ^5.9.3

  # Google Fonts
  google_fonts: ^6.2.1
  geolocator: ^14.0.3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
